[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "device_control"
description = "SCExAO device control"
readme = "README.md"
authors = [
    {name = "Miles Lucas", email = "mdlucas@hawaii.edu"},
    {name = "Vincent Deo", email = "vdeo@naoj.org"}
]
dependencies = [
    "click",
    "docopt==0.6.*",
    "pyserial>=3,<4",
    "tomli",
    "tomli-w",
    "zaber-motion>=2,<3",
    "tqdm>=4,<5",
    "swmain",
    "scxconf"
]
dynamic = ["version"]

[project.optional-dependencies]
test = [
    "pytest==7.*",
]

[project.scripts]
# daemons
vampires_daemon = "device_control.daemons.vampires_daemon:main"
# VAMPIRES devices
vampires_beamsplitter = "device_control.vampires.vampires_beamsplitter:main"
vampires_camfocus = "device_control.vampires.vampires_camfocus:main"
vampires_diffwheel = "device_control.vampires.vampires_diffwheel:main"
vampires_fieldstop = "device_control.vampires.cli.vampires_fieldstop:main"
vampires_filter = "device_control.vampires.vampires_filter:main"
vampires_flc = "device_control.vampires.vampires_flc:main"
vampires_focus = "device_control.vampires.vampires_focus:main"
vampires_mask = "device_control.vampires.vampires_mask:main"
vampires_mbi = "device_control.vampires.vampires_mbi:main"
vampires_pupil = "device_control.vampires.vampires_pupil:main"
vampires_qwp = "device_control.vampires.vampires_qwp:main"
vampires_tc = "device_control.vampires.vampires_tc:main"

[tool.setuptools.dynamic]
version = {attr = "device_control.__version__"}

[tool.coverage.run]
source = ["device_control"]
