name = "vampires_fieldstop"
configurations = [
    {idx=1, name="Open", value={x=3.5, y=3}},
    {idx=2, name="Field Stop (192 px)", value={x=3.5, y=13}},
    {idx=3, name="Field Stop (129 px)", value={x=3, y=23}},
    {idx=4, name="Field Stop (64 px)", value={x=13, y=23}},
    {idx=5, name="Open", value={x=13.57, y=13.5}},
    {idx=6, name="CLC-2 (36 mas IWA)", value={x=13.57, y=13.5}},
    {idx=7, name="CLC-3 (55 mas IWA)", value={x=23.548, y=13.431}},
    {idx=8, name="CLC-5 (92 mas IWA)", value={x=23.507, y=3.295}},
    {idx=9, name="CLC-7 (129 mas IWA)", value={x=13.706, y=3.291}},
]

[vampires_fieldstop.x]
type = "conex"
unit = "mm"
[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"

[vampires_fieldstop.y]
type = "conex"
unit = "mm"
[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
