name = "viswfs_rs2"
configurations = [
    { idx = 1, name = "Dichroic", value = 0.0 },
    { idx = 2, name = "PBS", value = 112.4 },
    { idx = 3, name = "Mirror", value = 243.8 },
]
unit = "deg"
offset = 0

[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A66UJDMO-if00-port0"
baudrate = 921600
xonxoff = true
