name = "vampires_fieldstop"
configurations = [
    { idx = 1, name = "Fieldstop", value = { x = 4.2473, y = 21.4188, f = 4.75 } },
    { idx = 2, name = "CLC-2", value = { x = 7.359999, y = 2.8017, f = 4.7472 } },
    { idx = 3, name = "CLC-3", value = { x = 7.357199, y = 9.040298, f = 4.75 } },
    { idx = 4, name = "CLC-5", value = { x = 1.1181, y = 9.043999, f = 4.75 } },
    { idx = 5, name = "CLC-7", value = { x = 1.1194, y = 2.7954, f = 4.75 } },
    { idx = 6, name = "DGVVC", value = { x = 19.7633, y = 21.3777, f = 5.234299 } },
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "y"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "f"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H3XPH-if00-port0"
baudrate = 921600
xonxoff = true
