name = "vampires_fieldstop"
configurations = [
    { idx = 1, name = "Fieldstop", value = { x = 4.2992, y = 22.1788, f = 4.991 } },
    { idx = 2, name = "CLC-2", value = { x = 7.335999, y = 3.4685, f = 4.990999 } },
    { idx = 3, name = "CLC-3", value = { x = 7.341199, y = 9.714199, f = 4.991 } },
    { idx = 4, name = "CLC-5", value = { x = 1.098, y = 9.717999, f = 4.990999 } },
    { idx = 5, name = "CLC-7", value = { x = 1.1082, y = 3.4683, f = 4.990999 } },
    { idx = 6, name = "DGVVC", value = { x = 19.7053, y = 22.0706, f = 5.2342 } },
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "y"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "f"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H3XPH-if00-port0"
baudrate = 921600
xonxoff = true
