name = "vampires_fieldstop"
configurations = [
    {idx=1, name="fieldstop", value={x=5.45, y=20.6}},
    {idx=2, name="CLC2", value={x=1.97, y=10.2}},
    {idx=3, name="CLC3", value={x=1.97, y=3.30}},
    {idx=4, name="CLC5", value={x=8.53, y=3.30}},
    {idx=5, name="CLC7", value={x=8.53, y=10.2}},
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"

[devices.serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"

[[devices]]
name = "y"
type = "conex"
unit = "mm"

[devices.serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"

