name = "vampires_camfocus"
configurations = [
    { idx = 1, name = "DUAL", value = 10.199989125000002 },
    { idx = 2, name = "SINGLE", value = 13.200221250000002 },
    { idx = 3, name = "PUPIL", value = 23.999999625 },
]
unit = "mm"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 3
