name = "vampires_mask"

[[configurations]]
idx = 1
name = "Open"

[configurations.value]
x = 9.477
y = 6.858
theta = 0

[[configurations]]
idx = 2
name = "SAM-7"

[configurations.value]
x = 7.213044375000001
y = 9.743932125
theta = 28.00016

[[configurations]]
idx = 3
name = "SAM-9"

[configurations.value]
x = 7.357919625000001
y = 5.18893425
theta = 48.30029

[[configurations]]
idx = 4
name = "SAM-18"

[configurations.value]
x = 7.498937250000001
y = 6.319980375
theta = 73.00015

[[configurations]]
idx = 5
name = "SAM-18-Nudged"

[configurations.value]
x = 7.110031500000001
y = 3.671935125
theta = 95.30022

[[configurations]]
idx = 6
name = "SAM-Ann-Nudged"

[configurations.value]
x = 7.3220103750000005
y = 4.572000000000001
theta = 120.0002

[[configurations]]
idx = 7
name = "Mirror"

[configurations.value]
x = 8.253
y = 5.153
theta = 143

[[configurations]]
idx = 8
name = "SAM-Ann"

[configurations.value]
x = 8.087
y = 10
theta = 164

[[configurations]]
idx = 9
name = "LyotStop"

[configurations.value]
x = 7.352014125
y = 4.935997875000001
theta = 191.9996

[[configurations]]
idx = 10
name = "Open"

[configurations.value]
x = 7.12
y = 6.858
theta = 217.5

[[configurations]]
idx = 11
name = "ND10"

[configurations.value]
x = 7.048
y = 6.858
theta = 241

[[configurations]]
idx = 12
name = "ND25"

[configurations.value]
x = 7.048
y = 6.858
theta = 265

[[configurations]]
idx = 13
name = "SAM-Ann-Ref"

[configurations.value]
x = 7.048
y = 6.858
theta = 283.2

[[devices]]
name = "x"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 1

[[devices]]
name = "y"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 2 

[[devices]]
name = "theta"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A6VRT271-if00-port0"
baudrate = 921600
xonxoff = true
