unit = "mm"
configurations = [
    {idx=1, name="in", value=0},
    {idx=2, name="out", value=50},
]
[serial]
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 4
