name = "vampires_mbi"
unit = "deg"
configurations = [
    {idx=1, name="IN", value=80},
    {idx=2, name="OUT", value=260},
]

[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H119F-if00-port0"
baudrate = 921600
xonxoff = true