name = "vampires_fieldstop"
configurations = [
    { idx = 1, name = "Fieldstop", value = { x = 5.632099, y = 20.7559 } },
    { idx = 2, name = "CLC-2", value = { x = 8.804099, y = 1.9664 } },
    { idx = 3, name = "CLC-3", value = { x = 8.804199, y = 8.212999 } },
    { idx = 4, name = "CLC-5", value = { x = 2.5483, y = 8.212999 } },
    { idx = 5, name = "CLC-7", value = { x = 2.5551, y = 1.9701 } },
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "y"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
baudrate = 921600
xonxoff = true
