name = "vampires_beamsplitter"
configurations = [
    { idx = 1, name = "Open", value = 0.0 },
    { idx = 2, name = "PBS", value = 90 },
    { idx = 3, name = "Open", value = 180 },
    { idx = 4, name = "NPBS", value = 269.3206 },
]
unit = "deg"
offset = 0

[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60QBY6C-if00-port0"
baudrate = 921600
xonxoff = true
