name = "vampires_mask"

[[configurations]]
idx = 1
name = "Open"

[configurations.value]
x = 7.799974875000001
y = 5.858017875000001
theta = 0.0004953764

[[configurations]]
idx = 2
name = "SAM-7"

[configurations.value]
x = 8.153019
y = 10.283999625
theta = 28.00076

[[configurations]]
idx = 3
name = "SAM-9"

[configurations.value]
x = 8.37790425
y = 5.528833875
theta = 48.30059

[[configurations]]
idx = 4
name = "SAM-18"

[configurations.value]
x = 8.358901874999999
y = 6.279975375
theta = 73.00045

[[configurations]]
idx = 5
name = "SAM-18-Nudged"

[configurations.value]
x = 9.002791875000002
y = 4.352020125000001
theta = 95.30121

[[configurations]]
idx = 6
name = "SAM-Ann-Nudged"

[configurations.value]
x = 8.30199
y = 4.9120425
theta = 120.0005

[[configurations]]
idx = 7
name = "Mirror"

[configurations.value]
x = 7.2529541250000005
y = 4.152947625
theta = 143.0002

[[configurations]]
idx = 8
name = "SAM-Ann"

[configurations.value]
x = 8.107013250000001
y = 0.10001250000000002
theta = 164.0

[[configurations]]
idx = 9
name = "LyotStop"

[configurations.value]
x = 9.234916125000002
y = 4.439269125
theta = 190.9045

[[configurations]]
idx = 10
name = "Open"

[configurations.value]
x = 7.4170222500000005
y = 6.8580000000000005
theta = 217.5011

[[configurations]]
idx = 11
name = "ND10"

[configurations.value]
x = 8.048005875
y = 5.858017875000001
theta = 241.0004

[[configurations]]
idx = 12
name = "ND25"

[configurations.value]
x = 8.048005875
y = 5.858017875000001
theta = 265.0002

[[configurations]]
idx = 13
name = "SAM-Ann-Ref"

[configurations.value]
x = 9.807940125000002
y = 3.758041125
theta = 286.2

[[devices]]
name = "x"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 1

[[devices]]
name = "y"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 2

[[devices]]
name = "theta"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A6VRT271-if00-port0"
baudrate = 921600
xonxoff = true
