name = "vampires_fieldstop"
configurations = [
    {idx=1, name="Fieldstop", value={x=5.45, y=20.6}},
    {idx=2, name="CLC-2", value={x=2.43, y=8.19}},
    {idx=3, name="CLC-3", value={x=2.43, y=2.15}},
    {idx=4, name="CLC-5", value={x=8.47, y=2.15}},
    {idx=5, name="CLC-7", value={x=8.47, y=8.19}},
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"

[devices.serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "y"
type = "conex"
unit = "mm"

[devices.serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
baudrate = 921600
xonxoff = true
