name = "vampires_camfocus"
configurations = [
    { idx = 1, name = "Dual", value = 10.440895480738632 },
    { idx = 2, name = "Single", value = 1.2999720000000001 },
    { idx = 3, name = "Pupil", value = 23.999999625 },
    { idx = 4, name = "Defocus", value = 8.199989125000002 },
]
unit = "mm"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 3
