name = "vampires_pupil"

configurations = [
    {idx=1, name="in", value="up"},
    {idx=2, name="out", value="down"}
]

[serial]
port = "/dev/serial/by-id/usb-Thorlabs_APT_Filter_Flipper_37004811-if00-port0"
baudrate = 115200
rtscts = true
