name = "vampires_beamsplitter"
unit = "deg"
configurations = [
    {idx=1, name="Open", value=0.0},
    {idx=2, name="PBS", value=45},
    {idx=3, name="Open", value=90},
    {idx=4, name="700SP", value=133.95},
    {idx=5, name="Open", value=180},
    {idx=6, name="NPBS", value=224.65},
    {idx=7, name="Open", value=270},
    {idx=8, name="750SP", value=315},
]

[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60QBY6C-if00-port0"
baudrate = 921600
xonxoff = true
