name = "vampires_focus"
unit = "mm"
configurations = [
    {idx=1, name="dualcam", value=12.0},
    {idx=2, name="single", value=7.8},
]

[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A6Z9D9VP-if00-port0"
baudrate = 921600
xonxoff = true
