name = "vampires_mbi"
configurations = [
    { idx = 1, name = "DICHROICS", value = 79.75016 },
    { idx = 2, name = "MIRROR", value = 258.2296 },
]
unit = "deg"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H119F-if00-port0"
baudrate = 921600
xonxoff = true
