name = "vampires_mbi"
configurations = [
    { idx = 1, name = "Dichroics", value = 79.97741 },
    { idx = 2, name = "Mirror", value = 258.2476 },
]
unit = "deg"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H119F-if00-port0"
baudrate = 921600
xonxoff = true
