name = "vampires_focus"
unit = "mm"
configurations = [
    {idx=1, name="standard", value=2},
    {idx=2, name="pupil", value=11},
    {idx=3, name="SDI", value=3},
]

[serial]
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A6Z9D9VP-if00-port0"
baudrate = 921600
xonxoff = true
