name = "vampires_diffwheel"
unit = "deg"
configurations = [
    {idx=1, name="open / open", value=0},
    {idx=2, name="Halpha / Ha-cont", value=60},
    {idx=3, name="SII / SII-cont", value=120},
    {idx=4, name="open / open", value=180},
    {idx=5, name="Ha-cont / Halpha", value=240},
    {idx=6, name="SII-cont / Halpha", value=300},
]
[serial]
port = "/dev/serial/by-id/usb-FTDI_USB-RS422_Cable_FT0B42PZ-if00-port0"
baudrate = 921600
xonxoff = true